services:
  synapsed-api:
    build:
      context: agents
      dockerfile: Dockerfile
    image: taut0logy/synapsed-api
    container_name: synapsed-api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PORT=5000
      - FLASK_ENV=production
      - DEBUG=False
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - synapsed-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
  
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: taut0logy/synapsed-client
    container_name: synapsed-client
    depends_on:
      - synapsed-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - synapsed-network

  # Uncomment if using nginx as a reverse proxy
  # nginx:
  #   image: nginx:latest
  #   container_name: synapsed-nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl
  #     - ./nginx/logs:/var/log/nginx
  #   depends_on:
  #     - synapsed-api
  #   networks:
  #     - synapsed-network

networks:
  synapsed-network:
    driver: bridge

volumes:
  storage:
    driver: local
  logs:
    driver: local